#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xdg-desktop-portal-gtk
Version  : 1.0.1
Release  : 3
URL      : https://github.com/flatpak/xdg-desktop-portal-gtk/releases/download/1.0.1/xdg-desktop-portal-gtk-1.0.1.tar.xz
Source0  : https://github.com/flatpak/xdg-desktop-portal-gtk/releases/download/1.0.1/xdg-desktop-portal-gtk-1.0.1.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
Requires: xdg-desktop-portal-gtk-config
Requires: xdg-desktop-portal-gtk-bin
Requires: xdg-desktop-portal-gtk-data
Requires: xdg-desktop-portal-gtk-license
Requires: xdg-desktop-portal-gtk-locales
BuildRequires : gettext
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(gio-unix-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(gtk+-unix-print-3.0)
BuildRequires : pkgconfig(gtk+-wayland-3.0)
BuildRequires : pkgconfig(gtk+-x11-3.0)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(xdg-desktop-portal)
BuildRequires : sed

%description
No detailed description available

%package bin
Summary: bin components for the xdg-desktop-portal-gtk package.
Group: Binaries
Requires: xdg-desktop-portal-gtk-data
Requires: xdg-desktop-portal-gtk-config
Requires: xdg-desktop-portal-gtk-license

%description bin
bin components for the xdg-desktop-portal-gtk package.


%package config
Summary: config components for the xdg-desktop-portal-gtk package.
Group: Default

%description config
config components for the xdg-desktop-portal-gtk package.


%package data
Summary: data components for the xdg-desktop-portal-gtk package.
Group: Data

%description data
data components for the xdg-desktop-portal-gtk package.


%package license
Summary: license components for the xdg-desktop-portal-gtk package.
Group: Default

%description license
license components for the xdg-desktop-portal-gtk package.


%package locales
Summary: locales components for the xdg-desktop-portal-gtk package.
Group: Default

%description locales
locales components for the xdg-desktop-portal-gtk package.


%prep
%setup -q -n xdg-desktop-portal-gtk-1.0.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1535723943
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1535723943
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/xdg-desktop-portal-gtk
cp COPYING %{buildroot}/usr/share/doc/xdg-desktop-portal-gtk/COPYING
%make_install
%find_lang xdg-desktop-portal-gtk

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/libexec/xdg-desktop-portal-gtk

%files config
%defattr(-,root,root,-)
/usr/lib/systemd/user/xdg-desktop-portal-gtk.service

%files data
%defattr(-,root,root,-)
/usr/share/applications/xdg-desktop-portal-gtk.desktop
/usr/share/dbus-1/services/org.freedesktop.impl.portal.desktop.gtk.service
/usr/share/xdg-desktop-portal/portals/gtk.portal

%files license
%defattr(-,root,root,-)
/usr/share/doc/xdg-desktop-portal-gtk/COPYING

%files locales -f xdg-desktop-portal-gtk.lang
%defattr(-,root,root,-)

