#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
# autospec version: v21
# autospec commit: f4a13a5
#
Name     : xdg-desktop-portal-gtk
Version  : 1.15.2
Release  : 18
URL      : https://github.com/flatpak/xdg-desktop-portal-gtk/releases/download/1.15.2/xdg-desktop-portal-gtk-1.15.2.tar.xz
Source0  : https://github.com/flatpak/xdg-desktop-portal-gtk/releases/download/1.15.2/xdg-desktop-portal-gtk-1.15.2.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
Requires: xdg-desktop-portal-gtk-data = %{version}-%{release}
Requires: xdg-desktop-portal-gtk-libexec = %{version}-%{release}
Requires: xdg-desktop-portal-gtk-license = %{version}-%{release}
Requires: xdg-desktop-portal-gtk-locales = %{version}-%{release}
Requires: xdg-desktop-portal-gtk-services = %{version}-%{release}
Requires: xdg-desktop-portal
BuildRequires : buildreq-meson
BuildRequires : glib-dev
BuildRequires : gnome-desktop-dev
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gnome-desktop-3.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(xdg-desktop-portal)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# xdg-desktop-portal-gtk
A backend implementation for [xdg-desktop-portal](http://github.com/flatpak/xdg-desktop-portal)
that is using GTK and various pieces of GNOME infrastructure, such as
org.gnome.desktop.* GSettings schemas and the org.gnome.SessionManager and
org.gnome.Screensaver D-Bus interfaces.

%package data
Summary: data components for the xdg-desktop-portal-gtk package.
Group: Data

%description data
data components for the xdg-desktop-portal-gtk package.


%package libexec
Summary: libexec components for the xdg-desktop-portal-gtk package.
Group: Default
Requires: xdg-desktop-portal-gtk-license = %{version}-%{release}

%description libexec
libexec components for the xdg-desktop-portal-gtk package.


%package license
Summary: license components for the xdg-desktop-portal-gtk package.
Group: Default

%description license
license components for the xdg-desktop-portal-gtk package.


%package locales
Summary: locales components for the xdg-desktop-portal-gtk package.
Group: Default

%description locales
locales components for the xdg-desktop-portal-gtk package.


%package services
Summary: services components for the xdg-desktop-portal-gtk package.
Group: Systemd services
Requires: systemd

%description services
services components for the xdg-desktop-portal-gtk package.


%prep
%setup -q -n xdg-desktop-portal-gtk-1.15.2
cd %{_builddir}/xdg-desktop-portal-gtk-1.15.2
pushd ..
cp -a xdg-desktop-portal-gtk-1.15.2 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1736455921
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir
GOAMD64=v3
CFLAGS="$CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " CXXFLAGS="$CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " LDFLAGS="$LDFLAGS -march=x86-64-v3 " meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddiravx2
ninja -v -C builddiravx2

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
mkdir -p %{buildroot}/usr/share/package-licenses/xdg-desktop-portal-gtk
cp %{_builddir}/xdg-desktop-portal-gtk-%{version}/COPYING %{buildroot}/usr/share/package-licenses/xdg-desktop-portal-gtk/01a6b4bf79aca9b556822601186afab86e8c4fbf || :
GOAMD64=v3
DESTDIR=%{buildroot}-v3 ninja -C builddiravx2 install
GOAMD64=v2
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang xdg-desktop-portal-gtk
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/applications/xdg-desktop-portal-gtk.desktop
/usr/share/dbus-1/services/org.freedesktop.impl.portal.desktop.gtk.service
/usr/share/xdg-desktop-portal/portals/gtk.portal

%files libexec
%defattr(-,root,root,-)
/V3/usr/libexec/xdg-desktop-portal-gtk
/usr/libexec/xdg-desktop-portal-gtk

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/xdg-desktop-portal-gtk/01a6b4bf79aca9b556822601186afab86e8c4fbf

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/user/xdg-desktop-portal-gtk.service

%files locales -f xdg-desktop-portal-gtk.lang
%defattr(-,root,root,-)

